import feladatok
print("1. feladat")
feladatok.elso_feladat()
print(" ")
print("2. feladat")
feladatok.masodik_feladat()
print(" ")
print("3. feladat")
feladatok.harmadik_feladat()
print(" ")
print("4. feladat")
feladatok.negyedik_feladat()
print(" ")
print("5. feladat")
feladatok.otodik_feladat()